### ISSUE TITLE
Migrate to Github Actions

### ISSUE THREAD

**Issue by gvolpe** [profunktor/http4s-tracer#160]
https://github.com/gvolpe/pfps-shopping-cart is a good example

**Comment by asachdeva** [comment]
@gvolpe I can help with this one as well.  Assuming with the move to github actions, one needs to also remove .circleci as well or do you want to keep both around?

**Comment by gvolpe** [comment]
Sure go ahead!

**Comment by asachdeva** [comment]
@gvolpe ....https://github.com/profunktor/http4s-tracer/pull/166  Thanks

**Comment by gvolpe** [comment]
closed by #166
